### ISSUE TITLE
Add relevant GUI images on `UserGuide`

### ISSUE THREAD

**Issue by RussellDash332** [AY2223S1-CS2103-F09-1/tp#153]
The UG is currently not that many of pictures. It would be nice to see what's going on for each feature performed.

**Comment by PokezardVGC** [comment]
I'm pushing this to V1.4b since need everyone to finish up with the bug fixging before we update in in UG.

**Comment by RussellDash332** [comment]
@PokezardVGC The latest UI update is on me so I'll assign this issue to myself as well.
