### ISSUE TITLE
[PE-D][Tester F] Display for deadlines are truncated in the GUI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F09-1/tp#160]
The display for deadlines is truncated, making it impossible to view the details of the task.
Perhaps some horizontal scrolling could be implemented to address this issue.

![image.png](https://raw.githubusercontent.com/marcusczh/ped/main/files/2262a27e-c3f5-4a86-b172-7ad5ef241489.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: marcusczh/ped#3

**Comment by RussellDash332** [comment]
Duplicate or related to #164
