### ISSUE TITLE
[PE-D][Tester G] Inaccurate error message for add deadline command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F09-1/tp#178]
![image.png](https://raw.githubusercontent.com/nqt230/ped/main/files/e9fce876-6a98-4cba-b7fe-ca0126568c9f.png)

Error message here should be that the student id given does not exist, but instead it's invalid date. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nqt230/ped#2

**Comment by RussellDash332** [comment]
This is due to how the deadline commands are parsed, which means it's related to #173.

**Comment by RussellDash332** [comment]
Fixed by #219.
