### ISSUE TITLE
[PE-D][Tester G] Recommendation: Allow case-insensitive status for marking project status 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F09-1/tp#182]
![image.png](https://raw.githubusercontent.com/nqt230/ped/main/files/272bada5-4780-42ff-92d1-c72bbd684d9e.png)

Allowing the user to input done or Done instead of DONE would make the command more flexible in keying in. 

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: nqt230/ped#3

**Comment by JordanChua** [comment]
Update in the UG instead

**Comment by RussellDash332** [comment]
> * Update in the UG such that parsing status is case-sensitive @PokezardVGC
> * Change OR to or -> Messages @JordanChua

Update, the second point is not feasible for v1.4
