### ISSUE TITLE
[PE-D][Tester F] Long load time for commands that change the GUI significantly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F09-1/tp#187]
Commands that change the GUI significantly such as find and list, take a few seconds to update the GUI when there are only 6 projects added. 
Some optimization may be needed to allow the app to handle seamless transitions for a large number of projects.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: marcusczh/ped#9

**Comment by RussellDash332** [comment]
Duplicate of #200
