### ISSUE TITLE
[PE-D][Tester C] List function did not work after using a find function

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F09-1/tp#193]
![Screenshot 2022-10-28 at 5.04.05 PM.png](https://raw.githubusercontent.com/danzzzerl/ped/main/files/1d52df72-0812-4a2b-b8a1-fedec4e05f23.png)
- list function deletes all data 
- restarting the application fixes this bug

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: danzzzerl/ped#5

**Comment by eugenelmj** [comment]
Closed after several testing and unable to replicate this issue.
Might be due to a lag that resulted in "list function deleting all data".
