### ISSUE TITLE
As a student with many email accounts, I can update my e-mail address when I change on the app

### ISSUE THREAD

**Issue by PokezardVGC** [AY2223S1-CS2103-F09-1/tp#26]
... so that I can be easily contacted by my professors when they need to find me.

**Comment by eugenelmj** [comment]
Maybe we should keep the personal details to e-mail address (phone number is more private...)

**Comment by PokezardVGC** [comment]
Thanks for the insights @eugenelmj , ammended it to emails

**Comment by RussellDash332** [comment]
Implemented in #137.
